import { tv } from 'tailwind-variants';

export const textStyles = tv({
  base: '',
  variants: {
    variant: {
      body: 'text-base leading-6',
      caption: 'text-sm leading-5',
      h1: 'text-6xl leading-none font-black',
      h2: 'text-4xl leading-10 font-bold',
      h3: 'text-3xl leading-9',
      h4: 'text-2xl leading-8 font-semibold',
      h5: 'text-xl leading-7 font-semibold',
      h6: 'text-base leading-6 font-semibold',
      subtitle: 'text-base leading-6',
      overline: 'text-sm leading-5 uppercase font-semibold tracking-wide',
      label: 'text-sm leading-5 font-medium',
      pageTitle: 'text-base leading-6 font-semibold uppercase tracking-wide',
    },
    textColor: {
      textPrimary: 'text-gray-900 dark:text-white',
      textSecondary: 'text-gray-700 dark:text-gray-200',
      textTertiary: 'text-gray-500 dark:text-gray-400',
      primary: 'text-primary-900 dark:text-primary-100',
      secondary: 'text-primary-700 dark:text-primary-200',
      tertiary: 'text-primary-500 dark:text-primary-400',
      infoPrimary: 'text-blue-900 dark:text-blue-100',
      infoSecondary: 'text-blue-700 dark:text-blue-200',
      infoTertiary: 'text-blue-500 dark:text-blue-400',
      successPrimary: 'text-green-900 dark:text-green-100',
      successSecondary: 'text-green-700 dark:text-green-200',
      successTertiary: 'text-green-500 dark:text-green-400',
      warningPrimary: 'text-amber-900 dark:text-amber-100',
      warningSecondary: 'text-amber-700 dark:text-amber-200',
      warningTertiary: 'text-amber-500 dark:text-amber-400',
      errorPrimary: 'text-red-900 dark:text-red-100',
      errorSecondary: 'text-red-700 dark:text-red-200',
      errorTertiary: 'text-red-500 dark:text-red-400',
      white: 'text-white',
      inherit: 'text-inherit',
    },
    textAlign: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
  },
  defaultVariants: {
    variant: 'body',
    textColor: 'textPrimary',
    textAlign: 'left',
  },
});
